// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBl-JbbDb-RCDzZS7ETO8BmBIahndR-s0',
    appId: '1:1031845016855:web:ef623e7a65b53e8b30b352',
    messagingSenderId: '1031845016855',
    projectId: 'intagram-e2dea',
    authDomain: 'intagram-e2dea.firebaseapp.com',
    storageBucket: 'intagram-e2dea.appspot.com',
    measurementId: 'G-KBL07LBSSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfarGMxdOUj0xMN8x6wFaHAwSp69uJ3Gw',
    appId: '1:1031845016855:android:85d0af2981afbab030b352',
    messagingSenderId: '1031845016855',
    projectId: 'intagram-e2dea',
    storageBucket: 'intagram-e2dea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdA-bwgBxFG6GyvrA7OjfCkXVqiFOAcA',
    appId: '1:1031845016855:ios:f7e73c1b8a6d25dc30b352',
    messagingSenderId: '1031845016855',
    projectId: 'intagram-e2dea',
    storageBucket: 'intagram-e2dea.appspot.com',
    iosClientId: '1031845016855-auno2j5fle7hssv512u7qi59gg2dlggm.apps.googleusercontent.com',
    iosBundleId: 'com.example.intagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdA-bwgBxFG6GyvrA7OjfCkXVqiFOAcA',
    appId: '1:1031845016855:ios:8be2e9ac0f5fefc130b352',
    messagingSenderId: '1031845016855',
    projectId: 'intagram-e2dea',
    storageBucket: 'intagram-e2dea.appspot.com',
    iosClientId: '1031845016855-h1b00lhdev5p8pubjth4ko5ie4fu9t4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.intagram.RunnerTests',
  );
}
